[package]
name = "bevy_editor_prototypes"
edition = "2021"
publish = false

[dependencies]
bevy = "0.14.0"

[workspace]
members = ["crates/*"]

[[bin]]
name = "bevy_editor"
path = "crates/bevy_editor/src/main.rs"
